city:
  name: "Islamabad"
  country: "Pakistan"
  latitude: 33.7298
  longitude: 73.1772
  aqicn_station: "@511588"   # ✅ SSPL, Islamabad (working station)

feature_store:
  project_name: "zeeshanproject"
  feature_group_name: "aqi_features"
  feature_group_version: 7